POST http://api.text.ru/account?method=get_packages_info&userkey=25d9645e0673d7d78979e230e3383faf

###

POST http://api.text.ru/post?userkey=25d9645e0673d7d78979e230e3383faf&text=Колезев отметил, что из-за отсутствия чёткого руководства город погряз в проблемах. Среди примеров он назвал

###

POST http://api.text.ru/post
Content-Type: application/x-www-form-urlencoded

userkey=25d9645e0673d7d78979e230e3383faf&text=Колезев отметил, что из-за отсутствия чёткого руководства город погряз в проблемах. Среди примеров он назвал

###


POST http://api.text.ru/post
Content-Type: application/x-www-form-urlencoded

uid=5a3f6edb1155e&userkey=25d9645e0673d7d78979e230e3383faf&jsonvisible=detail

###