POST http://api.text.ru/account?method=get_packages_info&userkey=25d9645e0673d7d78979e230e3383faf

###

POST http://api.text.ru/post?userkey=25d9645e0673d7d78979e230e3383faf&text=Колезев отметил, что из-за отсутствия чёткого руководства город погряз в проблемах. Среди примеров он назвал не только плохое благоустройство центральных улиц мегаполиса, которые за год до Чемпионата мира по футболу.